### ISSUE TITLE
cannot open the connection to 'http://rest.kegg.jp/link/ko/path:map00190

### ISSUE THREAD

**Issue by kriowloo** [hscleandro/FUNN-MG#1]
I'm getting this error when I'm trying to run FUNN over some metagenomic samples. 

`TERM environment variable not set.
Error in file(con, "r") :
  cannot open the connection to 'http://rest.kegg.jp/link/ko/path:map00190'
Calls: source ... withVisible -> eval -> eval -> KeggLink -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'http://rest.kegg.jp/link/ko/path:map00190': HTTP status was '403 Forbidden'
Execution halted`

How can I fix it?

**Comment by hscleandro** [comment]
> I'm getting this error when I'm trying to run FUNN over some metagenomic samples.
> 
> `TERM environment variable not set. Error in file(con, "r") : cannot open the connection to 'http://rest.kegg.jp/link/ko/path:map00190' Calls: source ... withVisible -> eval -> eval -> KeggLink -> readLines -> file In addition: Warning message: In file(con, "r") : cannot open URL 'http://rest.kegg.jp/link/ko/path:map00190': HTTP status was '403 Forbidden' Execution halted`
> 
> How can I fix it?

Check your internet connection. There may be a loss of connection during execution.

**Comment by kriowloo** [comment]
Yep! That was it. It worked now. Thanks!
